image: freebsd/latest
sources:
- https://git.sr.ht/~sircmpwn/hare
- https://git.sr.ht/~sircmpwn/harec
- git://c9x.me/qbe.git
packages:
- binutils
- scdoc
triggers:
- action: email
  condition: failure
  to: "<~sircmpwn/hare-dev@lists.sr.ht>"
tasks:
- environment: |
    if [ "$BUILD_SUBMITTER" = "git.sr.ht" ] && [ "$GIT_REF" != "refs/heads/master" ]
    then
        complete-build
    fi
- qbe: |
    cd qbe
    make -j2 CC=cc PREFIX=/usr
    sudo make install PREFIX=/usr
- harec: |
    cd harec
    cp configs/freebsd.mk config.mk
    make -j2
    sudo make install
- hare: |
    cd hare
    cp configs/freebsd.mk config.mk
    make -j2
    sudo make install
- check: |
    cd hare
    make -j2 check
- check_with_libc: |
    cd hare
    hare test -lc
